### ISSUE TITLE
Gruntfile not found (again)

### ISSUE THREAD

**Issue by pamtbaau** [kokarn/atom-grunt-runner#73] opened 2015-11-23 16:19 UTC
Installed Atom on Windows 10, add package grunt-runner and got the error: Gruntfile not found.

Searched the web, searched though all related issues here, tried all offered solution but to no avail.

In Atom I added a project folder which I used to work on using Netbeans which shows and executes all tasks in my Gruntfile.js. Grunt was installed locally in the subfolder of the project.

I tried many Path variations in the settings for this package. I've installed grunt globally and tried more Path variations...

I'm lost.

**Comment by REJack** [comment] 2015-11-24 22:11
idk but i created a file named ``Gruntfile`` without ``.js`` then it worked.

he need to add ``Gruntfile.js & gruntfile.js`` to [this array](https://github.com/nickclaw/atom-grunt-runner/blob/8e2df9b639ddaa6cc7267d0170052208738b6010/lib/grunt-runner.coffee#L20)

**Comment by kwhc** [comment] 2015-11-28 23:03
+1

**Comment by ealves-pt** [comment] 2016-02-10 11:44
@REJack the array seems ok to me... Those values are used inside a ```require()``` and as far as I understand you should not include file extensions when you use require. So in fact the values on that array should be able to resolve for ```Gruntfile.js & gruntfile.js```.

But I can't reproduce this is issue again. But I will keep an eye open for it.

**Comment by kokarn** [comment] 2016-02-10 13:46
@ealves-pt I've added you as a contributor btw, as a little thanks for your great work <3

**Comment by ealves-pt** [comment] 2016-02-10 14:56
@kokarn glad to help mate :+1:

**Comment by ealves-pt** [comment] 2016-02-10 22:19
Duplicate #10. Several issues cause ```Error loading Gruntfile: gruntfile not found```. I will try to gather all the reported issues in one place and go through the code to try to understand a bit more the root of all evil.

**Comment by RoverWire** [comment] 2016-02-15 23:01
Hey @ealves-pt and @kokarn https://github.com/kokarn/atom-grunt-runner/pull/91

**Comment by kokarn** [comment] 2016-02-16 08:25
@pamtbaau @REJack @kwhc  Would you mind updating to the latest version (0.13.6) and see if that solves your issues?

**Comment by pamtbaau** [comment] 2016-02-16 08:41
Sorry @kokarn, I've uninstalled and stopped using Atom.

**Comment by kokarn** [comment] 2016-02-16 08:47
No problem, somebody else can probably reproduce :)

**Comment by RoverWire** [comment] 2016-02-16 18:10
I just checked last version, this seems to be resolved :+1:

**Comment by ealves-pt** [comment] 2016-02-16 21:24
Thanks @RoverWire. I'll close the issue and we can keep an eye open for this bug on the other similar issues.

**Closed** 2016-02-16 21:23 UTC
Labels: bug, duplicate
